# This is a basic workflow to help you get started with Actions

name: Build Android adhoc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-android-adhoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Getting the repo
        uses: actions/checkout@v3
      
      # Install Node  
      - name: Installing node
        uses: actions/setup-node@v3
        with: 
          node-version: 14

      # Install React Native CLI
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli

      # Install yarn dependencies
      - name: Install yarn dependencies
        run: |
          yarn install

      # Building bundle
      - name: Building bundle
        run: |
          yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

      # Build android
      - name: Build android
        env:
          KEYSTORE_ALIAS_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_ALIAS_PASSPHRASE }}
          KEYSTORE_ALIAS: ${{ secrets.STAGING_KEYSTORE_ALIAS }}
          KEYSTORE_PASSPHRASE: ${{ secrets.STAGING_KEYSTORE_PASSPHRASE }}
        run: |
          export VERSION_CODE=${{ github.run_number }}
          export VERSION_NAME=1.0.${{ github.run_number }}
          echo ${{ secrets.STAGING_KEYSTORE }} | base64 --decode > android/app/staging.keystore
          cd android && ./gradlew -PversCode=$VERSION_CODE -PversName=$VERSION_NAME :app:assembleStaging
      
      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: android/app/build/outputs/apk/staging/app-staging.apk

  upload-android:
    needs: build-android-adhoc
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: android_testers
          file: app-staging.apk
